// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AgentOptimizationResultActivity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "GENERATING")]
        #pragma warning disable CS1591
        Generating,
        #pragma warning restore CS1591
        [EnumMember(Value = "EVALUATING")]
        #pragma warning disable CS1591
        Evaluating,
        #pragma warning restore CS1591
        [EnumMember(Value = "GENERATING_VARIATION")]
        #pragma warning disable CS1591
        GeneratingVariation,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALIDATING")]
        #pragma warning disable CS1591
        Validating,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
    }
}
