// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    /// <summary>For custom and trace metrics, the success criteria</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiConfigsMetricListingRepSuccessCriteria
    {
        [EnumMember(Value = "HigherThanBaseline")]
        #pragma warning disable CS1591
        HigherThanBaseline,
        #pragma warning restore CS1591
        [EnumMember(Value = "LowerThanBaseline")]
        #pragma warning disable CS1591
        LowerThanBaseline,
        #pragma warning restore CS1591
    }
}
