// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AiConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigsAccess? Access { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigsAccess Access { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public long? CreatedAt { get; set; }
        /// <summary>Resources that depend on this config, grouped by type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigDependency>? Dependencies { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigDependency> Dependencies { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Evaluation metric key for this config</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EvaluationMetricKey { get; set; }
#nullable restore
#else
        public string EvaluationMetricKey { get; set; }
#endif
        /// <summary>List of evaluation metric keys for this config</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EvaluationMetricKeys { get; set; }
#nullable restore
#else
        public List<string> EvaluationMetricKeys { get; set; }
#endif
        /// <summary>Whether the evaluation metric is inverted, meaning a lower value is better if set as true</summary>
        public bool? IsInverted { get; set; }
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The location and content type of related resources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ParentAndSelfLinks? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ParentAndSelfLinks Links { get; set; }
#endif
        /// <summary>The maintainer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMaintainer? Maintainer { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMaintainer Maintainer { get; set; }
#endif
        /// <summary>The mode property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMode? Mode { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The site property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.CoreLink? Site { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.CoreLink Site { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public long? UpdatedAt { get; set; }
        /// <summary>The variations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigVariation>? Variations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigVariation> Variations { get; set; }
#endif
        /// <summary>The version property</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfig"/> and sets the default values.
        /// </summary>
        public AiConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_access", n => { Access = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigsAccess>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigsAccess.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetLongValue(); } },
                { "dependencies", n => { Dependencies = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigDependency>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigDependency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "evaluationMetricKey", n => { EvaluationMetricKey = n.GetStringValue(); } },
                { "evaluationMetricKeys", n => { EvaluationMetricKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "isInverted", n => { IsInverted = n.GetBoolValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ParentAndSelfLinks>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ParentAndSelfLinks.CreateFromDiscriminatorValue); } },
                { "_maintainer", n => { Maintainer = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMaintainer>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMaintainer.CreateFromDiscriminatorValue); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMode>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "_site", n => { Site = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CoreLink>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.CoreLink.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetLongValue(); } },
                { "variations", n => { Variations = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigVariation>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigVariation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigsAccess>("_access", Access);
            writer.WriteLongValue("createdAt", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigDependency>("dependencies", Dependencies);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("evaluationMetricKey", EvaluationMetricKey);
            writer.WriteCollectionOfPrimitiveValues<string>("evaluationMetricKeys", EvaluationMetricKeys);
            writer.WriteBoolValue("isInverted", IsInverted);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ParentAndSelfLinks>("_links", Links);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMaintainer>("_maintainer", Maintainer);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigMode>("mode", Mode);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CoreLink>("_site", Site);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteLongValue("updatedAt", UpdatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AiConfigVariation>("variations", Variations);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
