// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    /// <summary>To distinguish the kind of application</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApplicationRepKind
    {
        [EnumMember(Value = "browser")]
        #pragma warning disable CS1591
        Browser,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "server")]
        #pragma warning disable CS1591
        Server,
        #pragma warning restore CS1591
    }
}
