// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApprovalRequestResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of individual reviews of this approval request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ReviewResponse>? AllReviews { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ReviewResponse> AllReviews { get; set; }
#endif
        /// <summary>The member ID of the member who applied the approval request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppliedByMemberId { get; set; }
#nullable restore
#else
        public string AppliedByMemberId { get; set; }
#endif
        /// <summary>The service token ID of the service token which applied the approval request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppliedByServiceTokenId { get; set; }
#nullable restore
#else
        public string AppliedByServiceTokenId { get; set; }
#endif
        /// <summary>The appliedDate property</summary>
        public long? AppliedDate { get; set; }
        /// <summary>The approvalSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalSettings? ApprovalSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalSettings ApprovalSettings { get; set; }
#endif
        /// <summary>Details on any conflicting approval requests</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Conflict>? Conflicts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Conflict> Conflicts { get; set; }
#endif
        /// <summary>The creationDate property</summary>
        public long? CreationDate { get; set; }
        /// <summary>The customWorkflowMetadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.CustomWorkflowMeta? CustomWorkflowMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.CustomWorkflowMeta CustomWorkflowMetadata { get; set; }
#endif
        /// <summary>A human-friendly name for the approval request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The executionDate property</summary>
        public long? ExecutionDate { get; set; }
        /// <summary>The ID of this approval request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The instructions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseInstructionsItem>? Instructions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseInstructionsItem> Instructions { get; set; }
#endif
        /// <summary>The integrationMetadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationMetadata? IntegrationMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationMetadata IntegrationMetadata { get; set; }
#endif
        /// <summary>The location and content type of related resources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseLinksProperty? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseLinksProperty Links { get; set; }
#endif
        /// <summary>An array of member IDs. These members are notified to review the approval request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NotifyMemberIds { get; set; }
#nullable restore
#else
        public List<string> NotifyMemberIds { get; set; }
#endif
        /// <summary>ID of scheduled change to edit or delete</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperatingOnId { get; set; }
#nullable restore
#else
        public string OperatingOnId { get; set; }
#endif
        /// <summary>The ID of the member who requested the approval</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestorId { get; set; }
#nullable restore
#else
        public string RequestorId { get; set; }
#endif
        /// <summary>String representation of a resource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceId { get; set; }
#nullable restore
#else
        public string ResourceId { get; set; }
#endif
        /// <summary>Current status of the review of this approval request</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseReviewStatus? ReviewStatus { get; set; }
        /// <summary>The serviceKind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceKind { get; set; }
#nullable restore
#else
        public string ServiceKind { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.CopiedFromEnv? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.CopiedFromEnv Source { get; set; }
#endif
        /// <summary>Current status of the approval request</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseStatus? Status { get; set; }
        /// <summary>Version of the approval request</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponse"/> and sets the default values.
        /// </summary>
        public ApprovalRequestResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allReviews", n => { AllReviews = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ReviewResponse>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ReviewResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "appliedByMemberId", n => { AppliedByMemberId = n.GetStringValue(); } },
                { "appliedByServiceTokenId", n => { AppliedByServiceTokenId = n.GetStringValue(); } },
                { "appliedDate", n => { AppliedDate = n.GetLongValue(); } },
                { "approvalSettings", n => { ApprovalSettings = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalSettings>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalSettings.CreateFromDiscriminatorValue); } },
                { "conflicts", n => { Conflicts = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Conflict>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Conflict.CreateFromDiscriminatorValue)?.AsList(); } },
                { "creationDate", n => { CreationDate = n.GetLongValue(); } },
                { "customWorkflowMetadata", n => { CustomWorkflowMetadata = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CustomWorkflowMeta>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.CustomWorkflowMeta.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "executionDate", n => { ExecutionDate = n.GetLongValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "instructions", n => { Instructions = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseInstructionsItem>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseInstructionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "integrationMetadata", n => { IntegrationMetadata = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationMetadata>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationMetadata.CreateFromDiscriminatorValue); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseLinksProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseLinksProperty.CreateFromDiscriminatorValue); } },
                { "notifyMemberIds", n => { NotifyMemberIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "operatingOnId", n => { OperatingOnId = n.GetStringValue(); } },
                { "requestorId", n => { RequestorId = n.GetStringValue(); } },
                { "resourceId", n => { ResourceId = n.GetStringValue(); } },
                { "reviewStatus", n => { ReviewStatus = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseReviewStatus>(); } },
                { "serviceKind", n => { ServiceKind = n.GetStringValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CopiedFromEnv>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.CopiedFromEnv.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseStatus>(); } },
                { "_version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ReviewResponse>("allReviews", AllReviews);
            writer.WriteStringValue("appliedByMemberId", AppliedByMemberId);
            writer.WriteStringValue("appliedByServiceTokenId", AppliedByServiceTokenId);
            writer.WriteLongValue("appliedDate", AppliedDate);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalSettings>("approvalSettings", ApprovalSettings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Conflict>("conflicts", Conflicts);
            writer.WriteLongValue("creationDate", CreationDate);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CustomWorkflowMeta>("customWorkflowMetadata", CustomWorkflowMetadata);
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("executionDate", ExecutionDate);
            writer.WriteStringValue("_id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseInstructionsItem>("instructions", Instructions);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationMetadata>("integrationMetadata", IntegrationMetadata);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseLinksProperty>("_links", Links);
            writer.WriteCollectionOfPrimitiveValues<string>("notifyMemberIds", NotifyMemberIds);
            writer.WriteStringValue("operatingOnId", OperatingOnId);
            writer.WriteStringValue("requestorId", RequestorId);
            writer.WriteStringValue("resourceId", ResourceId);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseReviewStatus>("reviewStatus", ReviewStatus);
            writer.WriteStringValue("serviceKind", ServiceKind);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CopiedFromEnv>("source", Source);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ApprovalRequestResponseStatus>("status", Status);
            writer.WriteIntValue("_version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
