// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BigSegmentStoreStatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the persistent store integration is fully synchronized with the LaunchDarkly environment, and the &lt;code&gt;lastSync&lt;/code&gt; occurred within a few minutes</summary>
        public bool? Available { get; set; }
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StoreIntegrationError>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StoreIntegrationError> Errors { get; set; }
#endif
        /// <summary>The lastError property</summary>
        public long? LastError { get; set; }
        /// <summary>The lastSync property</summary>
        public long? LastSync { get; set; }
        /// <summary>Whether the persistent store integration may not be fully synchronized with the LaunchDarkly environment. &lt;code&gt;true&lt;/code&gt; if the integration could be stale.</summary>
        public bool? PotentiallyStale { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.BigSegmentStoreStatus"/> and sets the default values.
        /// </summary>
        public BigSegmentStoreStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.BigSegmentStoreStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.BigSegmentStoreStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.BigSegmentStoreStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available", n => { Available = n.GetBoolValue(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StoreIntegrationError>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.StoreIntegrationError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastError", n => { LastError = n.GetLongValue(); } },
                { "lastSync", n => { LastSync = n.GetLongValue(); } },
                { "potentiallyStale", n => { PotentiallyStale = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("available", Available);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StoreIntegrationError>("errors", Errors);
            writer.WriteLongValue("lastError", LastError);
            writer.WriteLongValue("lastSync", LastSync);
            writer.WriteBoolValue("potentiallyStale", PotentiallyStale);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
