// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContextInstanceRecord : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access? Access { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access Access { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of the context kinds this context was associated with that the SDK removed because they were marked as anonymous at flag evaluation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AnonymousKinds { get; set; }
#nullable restore
#else
        public List<string> AnonymousKinds { get; set; }
#endif
        /// <summary>An identifier representing the application where the LaunchDarkly SDK is running</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationId { get; set; }
#nullable restore
#else
        public string ApplicationId { get; set; }
#endif
        /// <summary>The context, including its kind and attributes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordContext Context { get; set; }
#endif
        /// <summary>The context instance ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Timestamp of the last time an evaluation occurred for this context instance</summary>
        public DateTimeOffset? LastSeen { get; set; }
        /// <summary>The location and content type of related resources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordLinksProperty? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordLinksProperty Links { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecord"/> and sets the default values.
        /// </summary>
        public ContextInstanceRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_access", n => { Access = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access.CreateFromDiscriminatorValue); } },
                { "anonymousKinds", n => { AnonymousKinds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "applicationId", n => { ApplicationId = n.GetStringValue(); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordContext>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordContext.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastSeen", n => { LastSeen = n.GetDateTimeOffsetValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordLinksProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordLinksProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>("_access", Access);
            writer.WriteCollectionOfPrimitiveValues<string>("anonymousKinds", AnonymousKinds);
            writer.WriteStringValue("applicationId", ApplicationId);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordContext>("context", Context);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastSeen", LastSeen);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ContextInstanceRecordLinksProperty>("_links", Links);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
