// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DataExportProjectRankingScopeRep : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ranked dimension.</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ProjectDimension? Dimension { get; set; }
        /// <summary>Inclusive UTC range start in Unix milliseconds.</summary>
        public long? From { get; set; }
        /// <summary>The included usage source.</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.StreamingSource? Source { get; set; }
        /// <summary>Exclusive UTC range end in Unix milliseconds.</summary>
        public long? To { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.DataExportProjectRankingScopeRep"/> and sets the default values.
        /// </summary>
        public DataExportProjectRankingScopeRep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.DataExportProjectRankingScopeRep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.DataExportProjectRankingScopeRep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.DataExportProjectRankingScopeRep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dimension", n => { Dimension = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ProjectDimension>(); } },
                { "from", n => { From = n.GetLongValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StreamingSource>(); } },
                { "to", n => { To = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ProjectDimension>("dimension", Dimension);
            writer.WriteLongValue("from", From);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StreamingSource>("source", Source);
            writer.WriteLongValue("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
