// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeploymentRep : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether the deployment is active</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The application key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationKey { get; set; }
#nullable restore
#else
        public string ApplicationKey { get; set; }
#endif
        /// <summary>The application version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationVersion { get; set; }
#nullable restore
#else
        public string ApplicationVersion { get; set; }
#endif
        /// <summary>Whether the deployment is archived</summary>
        public bool? Archived { get; set; }
        /// <summary>The duration of the deployment in milliseconds</summary>
        public long? DurationMs { get; set; }
        /// <summary>The endedAt property</summary>
        public long? EndedAt { get; set; }
        /// <summary>The environment key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentKey { get; set; }
#nullable restore
#else
        public string EnvironmentKey { get; set; }
#endif
        /// <summary>The flagReferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagReferenceCollectionRep? FlagReferences { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagReferenceCollectionRep FlagReferences { get; set; }
#endif
        /// <summary>The deployment ID</summary>
        public Guid? Id { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The total lead time from first commit to deployment end in milliseconds</summary>
        public long? LeadTime { get; set; }
        /// <summary>The leadTimeStages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep? LeadTimeStages { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep LeadTimeStages { get; set; }
#endif
        /// <summary>The number of lines added</summary>
        public long? LinesAdded { get; set; }
        /// <summary>The number of lines deleted</summary>
        public long? LinesDeleted { get; set; }
        /// <summary>The metadata associated with the deployment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRepMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRepMetadataProperty Metadata { get; set; }
#endif
        /// <summary>The number of contributors</summary>
        public int? NumberOfContributors { get; set; }
        /// <summary>The number of pull requests</summary>
        public int? NumberOfPullRequests { get; set; }
        /// <summary>The pullRequests property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.PullRequestCollectionRep? PullRequests { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.PullRequestCollectionRep PullRequests { get; set; }
#endif
        /// <summary>The startedAt property</summary>
        public long? StartedAt { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRep"/> and sets the default values.
        /// </summary>
        public DeploymentRep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "applicationKey", n => { ApplicationKey = n.GetStringValue(); } },
                { "applicationVersion", n => { ApplicationVersion = n.GetStringValue(); } },
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "durationMs", n => { DurationMs = n.GetLongValue(); } },
                { "endedAt", n => { EndedAt = n.GetLongValue(); } },
                { "environmentKey", n => { EnvironmentKey = n.GetStringValue(); } },
                { "flagReferences", n => { FlagReferences = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagReferenceCollectionRep>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagReferenceCollectionRep.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "leadTime", n => { LeadTime = n.GetLongValue(); } },
                { "leadTimeStages", n => { LeadTimeStages = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep.CreateFromDiscriminatorValue); } },
                { "linesAdded", n => { LinesAdded = n.GetLongValue(); } },
                { "linesDeleted", n => { LinesDeleted = n.GetLongValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRepMetadataProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRepMetadataProperty.CreateFromDiscriminatorValue); } },
                { "numberOfContributors", n => { NumberOfContributors = n.GetIntValue(); } },
                { "numberOfPullRequests", n => { NumberOfPullRequests = n.GetIntValue(); } },
                { "pullRequests", n => { PullRequests = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.PullRequestCollectionRep>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.PullRequestCollectionRep.CreateFromDiscriminatorValue); } },
                { "startedAt", n => { StartedAt = n.GetLongValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteStringValue("applicationKey", ApplicationKey);
            writer.WriteStringValue("applicationVersion", ApplicationVersion);
            writer.WriteBoolValue("archived", Archived);
            writer.WriteLongValue("durationMs", DurationMs);
            writer.WriteLongValue("endedAt", EndedAt);
            writer.WriteStringValue("environmentKey", EnvironmentKey);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagReferenceCollectionRep>("flagReferences", FlagReferences);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("kind", Kind);
            writer.WriteLongValue("leadTime", LeadTime);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep>("leadTimeStages", LeadTimeStages);
            writer.WriteLongValue("linesAdded", LinesAdded);
            writer.WriteLongValue("linesDeleted", LinesDeleted);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.DeploymentRepMetadataProperty>("metadata", Metadata);
            writer.WriteIntValue("numberOfContributors", NumberOfContributors);
            writer.WriteIntValue("numberOfPullRequests", NumberOfPullRequests);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.PullRequestCollectionRep>("pullRequests", PullRequests);
            writer.WriteLongValue("startedAt", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
