// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    /// <summary>The type of Data Export destination</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DestinationKind
    {
        [EnumMember(Value = "google-pubsub")]
        #pragma warning disable CS1591
        GooglePubsub,
        #pragma warning restore CS1591
        [EnumMember(Value = "kinesis")]
        #pragma warning disable CS1591
        Kinesis,
        #pragma warning restore CS1591
        [EnumMember(Value = "mparticle")]
        #pragma warning disable CS1591
        Mparticle,
        #pragma warning restore CS1591
        [EnumMember(Value = "segment")]
        #pragma warning disable CS1591
        Segment,
        #pragma warning restore CS1591
        [EnumMember(Value = "azure-event-hubs")]
        #pragma warning disable CS1591
        AzureEventHubs,
        #pragma warning restore CS1591
        [EnumMember(Value = "snowflake-v2")]
        #pragma warning disable CS1591
        SnowflakeV2,
        #pragma warning restore CS1591
        [EnumMember(Value = "databricks")]
        #pragma warning disable CS1591
        Databricks,
        #pragma warning restore CS1591
        [EnumMember(Value = "bigquery")]
        #pragma warning disable CS1591
        Bigquery,
        #pragma warning restore CS1591
        [EnumMember(Value = "redshift")]
        #pragma warning disable CS1591
        Redshift,
        #pragma warning restore CS1591
    }
}
