// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExperimentPost : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The analysisConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AnalysisConfigInput? AnalysisConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.AnalysisConfigInput AnalysisConfig { get; set; }
#endif
        /// <summary>The source of metric data in order to analyze results. Defaults to &quot;launchdarkly&quot; when not provided.</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostDataSource? DataSource { get; set; }
        /// <summary>The experiment description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the holdout</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HoldoutId { get; set; }
#nullable restore
#else
        public string HoldoutId { get; set; }
#endif
        /// <summary>The iteration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IterationInput? Iteration { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IterationInput Iteration { get; set; }
#endif
        /// <summary>The experiment key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The ID of the member who maintains this experiment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintainerId { get; set; }
#nullable restore
#else
        public string MaintainerId { get; set; }
#endif
        /// <summary>The results analysis approach.</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostMethodology? Methodology { get; set; }
        /// <summary>The experiment name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Tags for the experiment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The type of experiment.</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPost"/> and sets the default values.
        /// </summary>
        public ExperimentPost()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPost"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPost CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPost();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "analysisConfig", n => { AnalysisConfig = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AnalysisConfigInput>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.AnalysisConfigInput.CreateFromDiscriminatorValue); } },
                { "dataSource", n => { DataSource = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostDataSource>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "holdoutId", n => { HoldoutId = n.GetStringValue(); } },
                { "iteration", n => { Iteration = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IterationInput>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IterationInput.CreateFromDiscriminatorValue); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "maintainerId", n => { MaintainerId = n.GetStringValue(); } },
                { "methodology", n => { Methodology = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostMethodology>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.AnalysisConfigInput>("analysisConfig", AnalysisConfig);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostDataSource>("dataSource", DataSource);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("holdoutId", HoldoutId);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IterationInput>("iteration", Iteration);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("maintainerId", MaintainerId);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostMethodology>("methodology", Methodology);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ExperimentPostType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
