// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeatureFlagBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The clientSideAvailability property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ClientSideAvailabilityPost? ClientSideAvailability { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.ClientSideAvailabilityPost ClientSideAvailability { get; set; }
#endif
        /// <summary>The customProperties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyCustomProperties? CustomProperties { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyCustomProperties CustomProperties { get; set; }
#endif
        /// <summary>The defaults property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Defaults? Defaults { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Defaults Defaults { get; set; }
#endif
        /// <summary>Description of the feature flag. Defaults to an empty string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Deprecated, use &lt;code&gt;clientSideAvailability&lt;/code&gt;. Whether this flag should be made available to the client-side JavaScript SDK. Defaults to &lt;code&gt;false&lt;/code&gt;.</summary>
        [Obsolete("")]
        public bool? IncludeInSnippet { get; set; }
        /// <summary>Initial set of prerequisite flags for all environments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagPrerequisitePost>? InitialPrerequisites { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagPrerequisitePost> InitialPrerequisites { get; set; }
#endif
        /// <summary>Whether to automatically turn the flag on across all environments at creation. Defaults to &lt;code&gt;false&lt;/code&gt;.</summary>
        public bool? IsFlagOn { get; set; }
        /// <summary>A unique key used to reference the flag in your code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The ID of the member who maintains this feature flag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintainerId { get; set; }
#nullable restore
#else
        public string MaintainerId { get; set; }
#endif
        /// <summary>The key of the team that maintains this feature flag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintainerTeamKey { get; set; }
#nullable restore
#else
        public string MaintainerTeamKey { get; set; }
#endif
        /// <summary>The migrationSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.MigrationSettingsPost? MigrationSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.MigrationSettingsPost MigrationSettings { get; set; }
#endif
        /// <summary>A human-friendly name for the feature flag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Purpose of the flag</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyPurpose? Purpose { get; set; }
        /// <summary>Tags for the feature flag. Defaults to an empty array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Whether the flag is a temporary flag. Defaults to &lt;code&gt;true&lt;/code&gt;.</summary>
        public bool? Temporary { get; set; }
        /// <summary>An array of possible variations for the flag. The variation values must be unique. If omitted, two boolean variations of &lt;code&gt;true&lt;/code&gt; and &lt;code&gt;false&lt;/code&gt; will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Variation>? Variations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Variation> Variations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBody"/> and sets the default values.
        /// </summary>
        public FeatureFlagBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clientSideAvailability", n => { ClientSideAvailability = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ClientSideAvailabilityPost>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.ClientSideAvailabilityPost.CreateFromDiscriminatorValue); } },
                { "customProperties", n => { CustomProperties = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyCustomProperties>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyCustomProperties.CreateFromDiscriminatorValue); } },
                { "defaults", n => { Defaults = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Defaults>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Defaults.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "includeInSnippet", n => { IncludeInSnippet = n.GetBoolValue(); } },
                { "initialPrerequisites", n => { InitialPrerequisites = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagPrerequisitePost>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagPrerequisitePost.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isFlagOn", n => { IsFlagOn = n.GetBoolValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "maintainerId", n => { MaintainerId = n.GetStringValue(); } },
                { "maintainerTeamKey", n => { MaintainerTeamKey = n.GetStringValue(); } },
                { "migrationSettings", n => { MigrationSettings = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.MigrationSettingsPost>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.MigrationSettingsPost.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "purpose", n => { Purpose = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyPurpose>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "temporary", n => { Temporary = n.GetBoolValue(); } },
                { "variations", n => { Variations = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Variation>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Variation.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.ClientSideAvailabilityPost>("clientSideAvailability", ClientSideAvailability);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyCustomProperties>("customProperties", CustomProperties);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Defaults>("defaults", Defaults);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("includeInSnippet", IncludeInSnippet);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagPrerequisitePost>("initialPrerequisites", InitialPrerequisites);
            writer.WriteBoolValue("isFlagOn", IsFlagOn);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("maintainerId", MaintainerId);
            writer.WriteStringValue("maintainerTeamKey", MaintainerTeamKey);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.MigrationSettingsPost>("migrationSettings", MigrationSettings);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FeatureFlagBodyPurpose>("purpose", Purpose);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteBoolValue("temporary", Temporary);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Variation>("variations", Variations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
