// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlagStatusRep : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Default value seen from code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepDefault? Default { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepDefault Default { get; set; }
#endif
        /// <summary>Timestamp of last time flag was requested</summary>
        public DateTimeOffset? LastRequested { get; set; }
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepLinksProperty? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepLinksProperty Links { get; set; }
#endif
        /// <summary>Status of the flag</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepName? Name { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRep"/> and sets the default values.
        /// </summary>
        public FlagStatusRep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default", n => { Default = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepDefault>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepDefault.CreateFromDiscriminatorValue); } },
                { "lastRequested", n => { LastRequested = n.GetDateTimeOffsetValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepLinksProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepLinksProperty.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepName>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepDefault>("default", Default);
            writer.WriteDateTimeOffsetValue("lastRequested", LastRequested);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepLinksProperty>("_links", Links);
            writer.WriteEnumValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.FlagStatusRepName>("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
