// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetLinkedResourcesExpandParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "maintainer")]
        #pragma warning disable CS1591
        Maintainer,
        #pragma warning restore CS1591
        [EnumMember(Value = "resourceDetails")]
        #pragma warning disable CS1591
        ResourceDetails,
        #pragma warning restore CS1591
    }
}
