// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    /// <summary>The type of change to make to the removal date for this user from individual targeting for this flag.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InstructionUserRequestKind
    {
        [EnumMember(Value = "addExpireUserTargetDate")]
        #pragma warning disable CS1591
        AddExpireUserTargetDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "updateExpireUserTargetDate")]
        #pragma warning disable CS1591
        UpdateExpireUserTargetDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "removeExpireUserTargetDate")]
        #pragma warning disable CS1591
        RemoveExpireUserTargetDate,
        #pragma warning restore CS1591
    }
}
