// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IntegrationDeliveryConfiguration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access? Access { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access Access { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationConfig Config { get; set; }
#endif
        /// <summary>The environment key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentKey { get; set; }
#nullable restore
#else
        public string EnvironmentKey { get; set; }
#endif
        /// <summary>The integration ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The integration key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationKey { get; set; }
#nullable restore
#else
        public string IntegrationKey { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationLinks? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationLinks Links { get; set; }
#endif
        /// <summary>Name of the configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Whether the configuration is turned on</summary>
        public bool? On { get; set; }
        /// <summary>The project key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectKey { get; set; }
#nullable restore
#else
        public string ProjectKey { get; set; }
#endif
        /// <summary>List of tags for this configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Version of the current configuration</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfiguration"/> and sets the default values.
        /// </summary>
        public IntegrationDeliveryConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_access", n => { Access = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access.CreateFromDiscriminatorValue); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationConfig>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationConfig.CreateFromDiscriminatorValue); } },
                { "environmentKey", n => { EnvironmentKey = n.GetStringValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "integrationKey", n => { IntegrationKey = n.GetStringValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationLinks>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationLinks.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "on", n => { On = n.GetBoolValue(); } },
                { "projectKey", n => { ProjectKey = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>("_access", Access);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationConfig>("config", Config);
            writer.WriteStringValue("environmentKey", EnvironmentKey);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("integrationKey", IntegrationKey);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationDeliveryConfigurationLinks>("_links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("on", On);
            writer.WriteStringValue("projectKey", ProjectKey);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
