// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Integration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access? Access { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access Access { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Datadog API key. Only used for legacy Datadog webhook integrations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKey { get; set; }
#nullable restore
#else
        public string ApiKey { get; set; }
#endif
        /// <summary>Details on configuration for an integration of this type. Refer to the &lt;code&gt;formVariables&lt;/code&gt; field in the corresponding &lt;code&gt;manifest.json&lt;/code&gt; for a full list of fields for each integration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationConfigProperty? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationConfigProperty Config { get; set; }
#endif
        /// <summary>The ID for this integration audit log subscription</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The type of integration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The location and content type of related resources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationLinksProperty? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationLinksProperty Links { get; set; }
#endif
        /// <summary>A human-friendly name for the integration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Whether the integration is currently active</summary>
        public bool? On { get; set; }
        /// <summary>Represents a Custom role policy, defining a resource kinds filter the integration audit log subscription responds to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement>? Statements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement> Statements { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationSubscriptionStatusRep? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationSubscriptionStatusRep Status { get; set; }
#endif
        /// <summary>An array of tags for this integration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Slack webhook receiver URL. Only used for legacy Slack webhook integrations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.Integration"/> and sets the default values.
        /// </summary>
        public Integration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.Integration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.Integration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.Integration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_access", n => { Access = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access.CreateFromDiscriminatorValue); } },
                { "apiKey", n => { ApiKey = n.GetStringValue(); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationConfigProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationConfigProperty.CreateFromDiscriminatorValue); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationLinksProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationLinksProperty.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "on", n => { On = n.GetBoolValue(); } },
                { "statements", n => { Statements = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "_status", n => { Status = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationSubscriptionStatusRep>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationSubscriptionStatusRep.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>("_access", Access);
            writer.WriteStringValue("apiKey", ApiKey);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationConfigProperty>("config", Config);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("kind", Kind);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationLinksProperty>("_links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("on", On);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement>("statements", Statements);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.IntegrationSubscriptionStatusRep>("_status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
