// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LeadTimeStagesRep : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The coding duration in milliseconds</summary>
        public long? CodingDurationMs { get; set; }
        /// <summary>The deploy duration in milliseconds</summary>
        public long? DeployDurationMs { get; set; }
        /// <summary>The review duration in milliseconds</summary>
        public long? ReviewDurationMs { get; set; }
        /// <summary>The total lead time in milliseconds</summary>
        public long? TotalLeadTimeMs { get; set; }
        /// <summary>The wait duration between merge time and deploy start time in milliseconds</summary>
        public long? WaitDurationMs { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep"/> and sets the default values.
        /// </summary>
        public LeadTimeStagesRep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.LeadTimeStagesRep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codingDurationMs", n => { CodingDurationMs = n.GetLongValue(); } },
                { "deployDurationMs", n => { DeployDurationMs = n.GetLongValue(); } },
                { "reviewDurationMs", n => { ReviewDurationMs = n.GetLongValue(); } },
                { "totalLeadTimeMs", n => { TotalLeadTimeMs = n.GetLongValue(); } },
                { "waitDurationMs", n => { WaitDurationMs = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("codingDurationMs", CodingDurationMs);
            writer.WriteLongValue("deployDurationMs", DeployDurationMs);
            writer.WriteLongValue("reviewDurationMs", ReviewDurationMs);
            writer.WriteLongValue("totalLeadTimeMs", TotalLeadTimeMs);
            writer.WriteLongValue("waitDurationMs", WaitDurationMs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
