// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MetricDenominatorRep : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dataSource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDataSourceRefRep? DataSource { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDataSourceRefRep DataSource { get; set; }
#endif
        /// <summary>The warehouse event column for the denominator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventName { get; set; }
#nullable restore
#else
        public string EventName { get; set; }
#endif
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Filter? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Filter Filters { get; set; }
#endif
        /// <summary>Whether the denominator aggregates a numeric value</summary>
        public bool? IsNumeric { get; set; }
        /// <summary>The column to count distinct values of; required when unitAggregationType is count_distinct</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitAggregationField { get; set; }
#nullable restore
#else
        public string UnitAggregationField { get; set; }
#endif
        /// <summary>How individual unit values are aggregated for the denominator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitAggregationType { get; set; }
#nullable restore
#else
        public string UnitAggregationType { get; set; }
#endif
        /// <summary>For a numeric denominator, the column holding the numeric value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValueColumn { get; set; }
#nullable restore
#else
        public string ValueColumn { get; set; }
#endif
        /// <summary>End of the measurement window in milliseconds</summary>
        public long? WindowEndOffset { get; set; }
        /// <summary>Start of the measurement window in milliseconds</summary>
        public long? WindowStartOffset { get; set; }
        /// <summary>When true, the percentile bound calculation includes imputed zeros</summary>
        public bool? WinsorIncludeImputed { get; set; }
        /// <summary>Lower winsorization percentile in the open interval (0, 100)</summary>
        public double? WinsorLowerPercentile { get; set; }
        /// <summary>Upper winsorization percentile in the open interval (0, 100)</summary>
        public double? WinsorUpperPercentile { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDenominatorRep"/> and sets the default values.
        /// </summary>
        public MetricDenominatorRep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDenominatorRep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDenominatorRep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDenominatorRep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dataSource", n => { DataSource = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDataSourceRefRep>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDataSourceRefRep.CreateFromDiscriminatorValue); } },
                { "eventName", n => { EventName = n.GetStringValue(); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Filter>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Filter.CreateFromDiscriminatorValue); } },
                { "isNumeric", n => { IsNumeric = n.GetBoolValue(); } },
                { "unitAggregationField", n => { UnitAggregationField = n.GetStringValue(); } },
                { "unitAggregationType", n => { UnitAggregationType = n.GetStringValue(); } },
                { "valueColumn", n => { ValueColumn = n.GetStringValue(); } },
                { "windowEndOffset", n => { WindowEndOffset = n.GetLongValue(); } },
                { "windowStartOffset", n => { WindowStartOffset = n.GetLongValue(); } },
                { "winsorIncludeImputed", n => { WinsorIncludeImputed = n.GetBoolValue(); } },
                { "winsorLowerPercentile", n => { WinsorLowerPercentile = n.GetDoubleValue(); } },
                { "winsorUpperPercentile", n => { WinsorUpperPercentile = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.MetricDataSourceRefRep>("dataSource", DataSource);
            writer.WriteStringValue("eventName", EventName);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Filter>("filters", Filters);
            writer.WriteBoolValue("isNumeric", IsNumeric);
            writer.WriteStringValue("unitAggregationField", UnitAggregationField);
            writer.WriteStringValue("unitAggregationType", UnitAggregationType);
            writer.WriteStringValue("valueColumn", ValueColumn);
            writer.WriteLongValue("windowEndOffset", WindowEndOffset);
            writer.WriteLongValue("windowStartOffset", WindowStartOffset);
            writer.WriteBoolValue("winsorIncludeImputed", WinsorIncludeImputed);
            writer.WriteDoubleValue("winsorLowerPercentile", WinsorLowerPercentile);
            writer.WriteDoubleValue("winsorUpperPercentile", WinsorUpperPercentile);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
