// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    /// <summary>The type of the metric group</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetricGroupPostKind
    {
        [EnumMember(Value = "funnel")]
        #pragma warning disable CS1591
        Funnel,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
    }
}
