// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    /// <summary>The type of unit aggregation to use for the metric</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetricInGroupRepUnitAggregationType
    {
        [EnumMember(Value = "sum")]
        #pragma warning disable CS1591
        Sum,
        #pragma warning restore CS1591
        [EnumMember(Value = "average")]
        #pragma warning disable CS1591
        Average,
        #pragma warning restore CS1591
        [EnumMember(Value = "count_distinct")]
        #pragma warning disable CS1591
        CountDistinct,
        #pragma warning restore CS1591
    }
}
