// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Team : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access? Access { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access Access { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creationDate property</summary>
        public long? CreationDate { get; set; }
        /// <summary>A description of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Whether the team has been synced with an external identity provider (IdP). Team sync is available to customers on an Enterprise plan.</summary>
        public bool? IdpSynced { get; set; }
        /// <summary>The team key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The lastModified property</summary>
        public long? LastModified { get; set; }
        /// <summary>The location and content type of related resources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamLinksProperty? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamLinksProperty Links { get; set; }
#endif
        /// <summary>The maintainers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMaintainers? Maintainers { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMaintainers Maintainers { get; set; }
#endif
        /// <summary>The members property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMembers? Members { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMembers Members { get; set; }
#endif
        /// <summary>A human-friendly name for the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The projects property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamProjects? Projects { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamProjects Projects { get; set; }
#endif
        /// <summary>The roleAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamRoleAttributes? RoleAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamRoleAttributes RoleAttributes { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamCustomRoles? Roles { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamCustomRoles Roles { get; set; }
#endif
        /// <summary>The team version</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.Team"/> and sets the default values.
        /// </summary>
        public Team()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.Team"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.Team CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.Team();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_access", n => { Access = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access.CreateFromDiscriminatorValue); } },
                { "_creationDate", n => { CreationDate = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "_idpSynced", n => { IdpSynced = n.GetBoolValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "_lastModified", n => { LastModified = n.GetLongValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamLinksProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamLinksProperty.CreateFromDiscriminatorValue); } },
                { "maintainers", n => { Maintainers = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMaintainers>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMaintainers.CreateFromDiscriminatorValue); } },
                { "members", n => { Members = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMembers>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMembers.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "projects", n => { Projects = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamProjects>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamProjects.CreateFromDiscriminatorValue); } },
                { "roleAttributes", n => { RoleAttributes = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamRoleAttributes>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamRoleAttributes.CreateFromDiscriminatorValue); } },
                { "roles", n => { Roles = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamCustomRoles>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamCustomRoles.CreateFromDiscriminatorValue); } },
                { "_version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Access>("_access", Access);
            writer.WriteLongValue("_creationDate", CreationDate);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("_idpSynced", IdpSynced);
            writer.WriteStringValue("key", Key);
            writer.WriteLongValue("_lastModified", LastModified);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamLinksProperty>("_links", Links);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMaintainers>("maintainers", Maintainers);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamMembers>("members", Members);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamProjects>("projects", Projects);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamRoleAttributes>("roleAttributes", RoleAttributes);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TeamCustomRoles>("roles", Roles);
            writer.WriteIntValue("_version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
