// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Token : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creationDate property</summary>
        public long? CreationDate { get; set; }
        /// <summary>A list of custom role IDs to use as access limits for the access token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomRoleIds { get; set; }
#nullable restore
#else
        public List<string> CustomRoleIds { get; set; }
#endif
        /// <summary>The default API version for this token</summary>
        public int? DefaultApiVersion { get; set; }
        /// <summary>A description for the access token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>An array of policy statements, with three attributes: effect, resources, actions. May be used in place of a role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement>? InlineRole { get; set; }
#nullable restore
#else
        public List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement> InlineRole { get; set; }
#endif
        /// <summary>The lastModified property</summary>
        public long? LastModified { get; set; }
        /// <summary>The lastUsed property</summary>
        public long? LastUsed { get; set; }
        /// <summary>The location and content type of related resources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TokenLinksProperty? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.TokenLinksProperty Links { get; set; }
#endif
        /// <summary>The member property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.MemberSummary? Member { get; set; }
#nullable restore
#else
        public global::Soenneker.LaunchDarkly.OpenApiClient.Models.MemberSummary Member { get; set; }
#endif
        /// <summary>The memberId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberId { get; set; }
#nullable restore
#else
        public string MemberId { get; set; }
#endif
        /// <summary>A human-friendly name for the access token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ownerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>Base role for the token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>Whether this is a service token or a personal token</summary>
        public bool? ServiceToken { get; set; }
        /// <summary>The token value. When creating or resetting, contains the entire token value. Otherwise, contains the last four characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenProp { get; set; }
#nullable restore
#else
        public string TokenProp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.Token"/> and sets the default values.
        /// </summary>
        public Token()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.Token"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.Token CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.Token();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creationDate", n => { CreationDate = n.GetLongValue(); } },
                { "customRoleIds", n => { CustomRoleIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "defaultApiVersion", n => { DefaultApiVersion = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "inlineRole", n => { InlineRole = n.GetCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastModified", n => { LastModified = n.GetLongValue(); } },
                { "lastUsed", n => { LastUsed = n.GetLongValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TokenLinksProperty>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.TokenLinksProperty.CreateFromDiscriminatorValue); } },
                { "_member", n => { Member = n.GetObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.MemberSummary>(global::Soenneker.LaunchDarkly.OpenApiClient.Models.MemberSummary.CreateFromDiscriminatorValue); } },
                { "memberId", n => { MemberId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "serviceToken", n => { ServiceToken = n.GetBoolValue(); } },
                { "token", n => { TokenProp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("creationDate", CreationDate);
            writer.WriteCollectionOfPrimitiveValues<string>("customRoleIds", CustomRoleIds);
            writer.WriteIntValue("defaultApiVersion", DefaultApiVersion);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("_id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.LaunchDarkly.OpenApiClient.Models.Statement>("inlineRole", InlineRole);
            writer.WriteLongValue("lastModified", LastModified);
            writer.WriteLongValue("lastUsed", LastUsed);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.TokenLinksProperty>("_links", Links);
            writer.WriteObjectValue<global::Soenneker.LaunchDarkly.OpenApiClient.Models.MemberSummary>("_member", Member);
            writer.WriteStringValue("memberId", MemberId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteStringValue("role", Role);
            writer.WriteBoolValue("serviceToken", ServiceToken);
            writer.WriteStringValue("token", TokenProp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
