// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WarehouseDestinationSetupScriptRep : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The RSA public key (Snowflake only) to store as the destination public_key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicKey { get; set; }
#nullable restore
#else
        public string PublicKey { get; set; }
#endif
        /// <summary>The PKCS8 RSA public key (Snowflake only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicKeyPkcs8 { get; set; }
#nullable restore
#else
        public string PublicKeyPkcs8 { get; set; }
#endif
        /// <summary>For Redshift, present only when clusterIdentifier, clusterRegion, and clusterAwsAccountId are supplied in the request body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedshiftIAMPermissionsPolicy { get; set; }
#nullable restore
#else
        public string RedshiftIAMPermissionsPolicy { get; set; }
#endif
        /// <summary>For Redshift, present only when clusterIdentifier, clusterRegion, and clusterAwsAccountId are supplied in the request body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedshiftIAMTrustPolicy { get; set; }
#nullable restore
#else
        public string RedshiftIAMTrustPolicy { get; set; }
#endif
        /// <summary>The auto-generated S3 staging bucket name (ClickHouse and Redshift)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? S3BucketName { get; set; }
#nullable restore
#else
        public string S3BucketName { get; set; }
#endif
        /// <summary>The SQL setup script to run in your data warehouse</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Script { get; set; }
#nullable restore
#else
        public string Script { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.WarehouseDestinationSetupScriptRep"/> and sets the default values.
        /// </summary>
        public WarehouseDestinationSetupScriptRep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.WarehouseDestinationSetupScriptRep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.LaunchDarkly.OpenApiClient.Models.WarehouseDestinationSetupScriptRep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Models.WarehouseDestinationSetupScriptRep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "publicKey", n => { PublicKey = n.GetStringValue(); } },
                { "publicKeyPkcs8", n => { PublicKeyPkcs8 = n.GetStringValue(); } },
                { "redshiftIAMPermissionsPolicy", n => { RedshiftIAMPermissionsPolicy = n.GetStringValue(); } },
                { "redshiftIAMTrustPolicy", n => { RedshiftIAMTrustPolicy = n.GetStringValue(); } },
                { "s3BucketName", n => { S3BucketName = n.GetStringValue(); } },
                { "script", n => { Script = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("publicKey", PublicKey);
            writer.WriteStringValue("publicKeyPkcs8", PublicKeyPkcs8);
            writer.WriteStringValue("redshiftIAMPermissionsPolicy", RedshiftIAMPermissionsPolicy);
            writer.WriteStringValue("redshiftIAMTrustPolicy", RedshiftIAMTrustPolicy);
            writer.WriteStringValue("s3BucketName", S3BucketName);
            writer.WriteStringValue("script", Script);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
