// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.GenerateTrustPolicy;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.GenerateWarehouseDestinationKeyPair;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.Kinds;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\destinations\projects\{projKey}\environments\{envKey}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEnvKeyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The generateTrustPolicy property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.GenerateTrustPolicy.GenerateTrustPolicyRequestBuilder GenerateTrustPolicy
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.GenerateTrustPolicy.GenerateTrustPolicyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The generateWarehouseDestinationKeyPair property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.GenerateWarehouseDestinationKeyPair.GenerateWarehouseDestinationKeyPairRequestBuilder GenerateWarehouseDestinationKeyPair
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.GenerateWarehouseDestinationKeyPair.GenerateWarehouseDestinationKeyPairRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The kinds property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.Kinds.KindsRequestBuilder Kinds
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.Kinds.KindsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.WithEnvKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnvKeyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/destinations/projects/{projKey}/environments/{envKey}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Destinations.Projects.Item.Environments.Item.WithEnvKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnvKeyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/destinations/projects/{projKey}/environments/{envKey}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
