// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.LaunchDarkly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\engineering-insights\charts\lead-time
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LeadTimeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadTimeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/engineering-insights/charts/lead-time?projectKey={projectKey}{&applicationKey*,bucketMs*,bucketType*,environmentKey*,expand*,from*,groupBy*,to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadTimeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/engineering-insights/charts/lead-time?projectKey={projectKey}{&applicationKey*,bucketMs*,bucketType*,environmentKey*,expand*,from*,groupBy*,to*}", rawUrl)
        {
        }
        /// <summary>
        /// Get lead time chart data. The engineering insights UI displays lead time data in the [lead time metric view](https://launchdarkly.com/docs/home/observability/lead-time).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.InsightsChart"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ValidationFailedErrorRep">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.UnauthorizedErrorRep">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ForbiddenErrorRep">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.NotFoundErrorRep">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.RateLimitedErrorRep">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.LaunchDarkly.OpenApiClient.Models.InsightsChart?> GetAsync(Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder.LeadTimeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.LaunchDarkly.OpenApiClient.Models.InsightsChart> GetAsync(Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder.LeadTimeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.LaunchDarkly.OpenApiClient.Models.ValidationFailedErrorRep.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.LaunchDarkly.OpenApiClient.Models.UnauthorizedErrorRep.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.LaunchDarkly.OpenApiClient.Models.ForbiddenErrorRep.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.LaunchDarkly.OpenApiClient.Models.NotFoundErrorRep.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.LaunchDarkly.OpenApiClient.Models.RateLimitedErrorRep.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.LaunchDarkly.OpenApiClient.Models.InsightsChart>(requestInfo, global::Soenneker.LaunchDarkly.OpenApiClient.Models.InsightsChart.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get lead time chart data. The engineering insights UI displays lead time data in the [lead time metric view](https://launchdarkly.com/docs/home/observability/lead-time).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder.LeadTimeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder.LeadTimeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.EngineeringInsights.Charts.LeadTime.LeadTimeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get lead time chart data. The engineering insights UI displays lead time data in the [lead time metric view](https://launchdarkly.com/docs/home/observability/lead-time).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LeadTimeRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma separated list of application keys</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("applicationKey")]
            public string? ApplicationKey { get; set; }
#nullable restore
#else
            [QueryParameter("applicationKey")]
            public string ApplicationKey { get; set; }
#endif
            /// <summary>Duration of intervals for x-axis in milliseconds. Default value is one day (`86400000` milliseconds).</summary>
            [QueryParameter("bucketMs")]
            public long? BucketMs { get; set; }
            /// <summary>Specify type of bucket. Options: `rolling`, `hour`, `day`. Default: `rolling`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bucketType")]
            public string? BucketType { get; set; }
#nullable restore
#else
            [QueryParameter("bucketType")]
            public string BucketType { get; set; }
#endif
            /// <summary>The environment key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environmentKey")]
            public string? EnvironmentKey { get; set; }
#nullable restore
#else
            [QueryParameter("environmentKey")]
            public string EnvironmentKey { get; set; }
#endif
            /// <summary>Options: `metrics`, `percentiles`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public string? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public string Expand { get; set; }
#endif
            /// <summary>Unix timestamp in milliseconds. Default value is 7 days ago.</summary>
            [QueryParameter("from")]
            public long? From { get; set; }
            /// <summary>Options: `application`, `stage`. Default: `stage`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("groupBy")]
            public string? GroupBy { get; set; }
#nullable restore
#else
            [QueryParameter("groupBy")]
            public string GroupBy { get; set; }
#endif
            /// <summary>The project key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("projectKey")]
            public string? ProjectKey { get; set; }
#nullable restore
#else
            [QueryParameter("projectKey")]
            public string ProjectKey { get; set; }
#endif
            /// <summary>Unix timestamp in milliseconds. Default value is now.</summary>
            [QueryParameter("to")]
            public long? To { get; set; }
        }
    }
}
#pragma warning restore CS0618
