// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.All;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.Details;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\usage\sdk-versions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SdkVersionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.All.AllRequestBuilder All
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The details property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.Details.DetailsRequestBuilder Details
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.Details.DetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.SdkVersionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SdkVersionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/usage/sdk-versions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.SdkVersionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SdkVersionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/usage/sdk-versions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
