// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.AiRuns;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ClientsideContexts;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ClientsideMau;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.DataExportEvents;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Evaluations;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Events;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ExperimentationEvents;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ExperimentationKeys;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Mau;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Observability;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ServersideContexts;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ServiceConnections;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Streams;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.TotalContexts;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.TotalMau;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.VegaAi;
using Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.WarehouseExport;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\usage
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The aiRuns property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.AiRuns.AiRunsRequestBuilder AiRuns
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.AiRuns.AiRunsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clientsideContexts property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ClientsideContexts.ClientsideContextsRequestBuilder ClientsideContexts
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ClientsideContexts.ClientsideContextsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clientsideMau property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ClientsideMau.ClientsideMauRequestBuilder ClientsideMau
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ClientsideMau.ClientsideMauRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataExportEvents property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.DataExportEvents.DataExportEventsRequestBuilder DataExportEvents
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.DataExportEvents.DataExportEventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The evaluations property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Evaluations.EvaluationsRequestBuilder Evaluations
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Evaluations.EvaluationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The experimentationEvents property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ExperimentationEvents.ExperimentationEventsRequestBuilder ExperimentationEvents
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ExperimentationEvents.ExperimentationEventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The experimentationKeys property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ExperimentationKeys.ExperimentationKeysRequestBuilder ExperimentationKeys
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ExperimentationKeys.ExperimentationKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mau property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Mau.MauRequestBuilder Mau
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Mau.MauRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The observability property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Observability.ObservabilityRequestBuilder Observability
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Observability.ObservabilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sdkVersions property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.SdkVersionsRequestBuilder SdkVersions
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.SdkVersions.SdkVersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serversideContexts property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ServersideContexts.ServersideContextsRequestBuilder ServersideContexts
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ServersideContexts.ServersideContextsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serviceConnections property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ServiceConnections.ServiceConnectionsRequestBuilder ServiceConnections
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.ServiceConnections.ServiceConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The streams property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Streams.StreamsRequestBuilder Streams
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.Streams.StreamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The totalContexts property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.TotalContexts.TotalContextsRequestBuilder TotalContexts
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.TotalContexts.TotalContextsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The totalMau property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.TotalMau.TotalMauRequestBuilder TotalMau
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.TotalMau.TotalMauRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vegaAi property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.VegaAi.VegaAiRequestBuilder VegaAi
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.VegaAi.VegaAiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The warehouseExport property</summary>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.WarehouseExport.WarehouseExportRequestBuilder WarehouseExport
        {
            get => new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.WarehouseExport.WarehouseExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.UsageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/usage", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Usage.UsageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/usage", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
