// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.LaunchDarkly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\auditlog\counts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/auditlog/counts?after={after}{&before*,buckets*,member*,token*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/auditlog/counts?after={after}{&before*,buckets*,member*,token*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns aggregate counts of audit log entries per time bucket. Used for dashboard overlays that show flag targeting changes.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.CountBucketsResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.InvalidRequestErrorRep">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.UnauthorizedErrorRep">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.ForbiddenErrorRep">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.LaunchDarkly.OpenApiClient.Models.RateLimitedErrorRep">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CountBucketsResult?> PostAsync(List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StatementPost> body, Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder.CountsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CountBucketsResult> PostAsync(List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StatementPost> body, Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder.CountsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.LaunchDarkly.OpenApiClient.Models.InvalidRequestErrorRep.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.LaunchDarkly.OpenApiClient.Models.UnauthorizedErrorRep.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.LaunchDarkly.OpenApiClient.Models.ForbiddenErrorRep.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.LaunchDarkly.OpenApiClient.Models.RateLimitedErrorRep.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.LaunchDarkly.OpenApiClient.Models.CountBucketsResult>(requestInfo, global::Soenneker.LaunchDarkly.OpenApiClient.Models.CountBucketsResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns aggregate counts of audit log entries per time bucket. Used for dashboard overlays that show flag targeting changes.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StatementPost> body, Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder.CountsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(List<global::Soenneker.LaunchDarkly.OpenApiClient.Models.StatementPost> body, Action<RequestConfiguration<global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder.CountsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.LaunchDarkly.OpenApiClient.Api.V2.Auditlog.Counts.CountsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns aggregate counts of audit log entries per time bucket. Used for dashboard overlays that show flag targeting changes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CountsRequestBuilderPostQueryParameters 
        {
            /// <summary>A timestamp filter, expressed as a Unix epoch time in milliseconds. Required.</summary>
            [QueryParameter("after")]
            public long? After { get; set; }
            /// <summary>A timestamp filter, expressed as a Unix epoch time in milliseconds. Defaults to now.</summary>
            [QueryParameter("before")]
            public long? Before { get; set; }
            /// <summary>Number of time buckets to divide the range into. Default 50, max 500.</summary>
            [QueryParameter("buckets")]
            public long? Buckets { get; set; }
            /// <summary>A member ID that lets you filter counts to changes made by that member. Repeat the parameter to filter by multiple members.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("member")]
            public string? Member { get; set; }
#nullable restore
#else
            [QueryParameter("member")]
            public string Member { get; set; }
#endif
            /// <summary>An access token ID that lets you filter counts to changes made by that token. Repeat the parameter to filter by multiple tokens.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("token")]
            public string? Token { get; set; }
#nullable restore
#else
            [QueryParameter("token")]
            public string Token { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
